# Render.com deployment configuration
services:
  # Main application service
  - type: web
    name: telegram-revenue-copilot
    env: docker
    plan: starter
    dockerfilePath: ./infra/Dockerfile.render
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: GOOGLE_SHEETS_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_SHEETS_OAUTH_CLIENT_SECRET
        sync: false
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: WEBHOOK_URL
        value: https://telegram-revenue-copilot.onrender.com

  # PostgreSQL database
  - type: pserv
    name: telegram-copilot-db
    env: postgres
    plan: starter
    envVars:
      - key: POSTGRES_DB
        value: n8n
      - key: POSTGRES_USER
        value: n8n

databases:
  - name: telegram-copilot-db
    databaseName: n8n
    user: n8n